#!/usr/bin/env python3
"""
Turn raw benchmark/correctness JSON into the LaTeX fragments the paper
\\inputs. Running this is the only way numbers enter the manuscript, so the
tables cannot drift from the measurements.

Every kernel size that appears in a caption or a row label is read from the
benchmark JSON's recorded arguments -- nothing here hard-codes k, so changing
`bench.py --kernel-size` propagates into the manuscript automatically.

Outputs (into --outdir, default ../results):
    tab_latency.tex         tab_latency_train.tex
    tab_memory.tex          tab_memory_inference.tex
    tab_absolute.tex        tab_correctness.tex
    per_config/tab_{speedup,memory}_<protocol>_<mode>_<dtype>.tex
    env.tex                 hardware/software line for the appendix
    macros.tex              every measured number the prose quotes
    tab_hardware.tex        cross-hardware validation summary (--bench-hardware only)
    env_hardware.tex        hardware/software line for the second GPU (--bench-hardware only)

Usage
-----
    python make_tables.py --bench ../results/bench_cuda.json \\
                          --correctness ../results/correctness.json \\
                          --bench-hardware ../results/bench_cuda_rtxpro6000.json
"""

from __future__ import annotations

import argparse
import json
import math
from collections import defaultdict
from pathlib import Path

BASELINE = "reference"          # denominator for every speedup ratio
DISPLAY = {
    "depthwise": r"Depthwise",
    "dense": r"Dense",
    "reference": r"WTConv~\citep{finder2024wavelet}",
    "fused_cuda": r"\textbf{Fused (CUDA)}",
}
ORDER = ["depthwise", "dense", "reference", "fused_cuda"]

# Rows of the combined results tables: (method, protocol, label template). The
# depthwise convolution appears twice, once per protocol, so that a single table
# carries both the matched-kernel-size and the drop-in-replacement baselines.
# Dense convolutions are measured but deliberately kept out of the paper tables:
# WTConv replaces a depthwise convolution, so that is the only comparison the
# manuscript makes. @K@ is the homogeneous kernel size, @KD@ the drop-in one;
# both come from the benchmark JSON. Sentinels rather than str.format, because
# the labels are LaTeX and full of braces.
PAPER_ROWS = [
    ("depthwise", "homogeneous", r"Depthwise conv, $k{=}@K@$"),
    ("depthwise", "dropin", r"Depthwise conv, $k{=}@KD@$"),
    ("reference", "homogeneous", r"WTConv, reference"),
    ("fused_cuda", "homogeneous", r"WTConv, \textbf{fused}"),
]
DTYPE_TEX = {"fp32": r"\texttt{fp32}", "fp16": r"\texttt{fp16}", "bf16": r"\texttt{bf16}"}

# --- macro naming ------------------------------------------------------------
# LaTeX control sequences cannot contain digits, so every axis value maps to a
# word. A macro is \<Metric><Row><Mode><Dtype><Agg>, e.g.
# \SpeedupFusedTrainFpThirtyTwoMax.
ROW_MACRO = {
    ("depthwise", "homogeneous"): "DepthwiseHom",
    ("dense", "homogeneous"): "DenseHom",
    ("depthwise", "dropin"): "DepthwiseDrop",
    ("dense", "dropin"): "DenseDrop",
    ("fused_cuda", "homogeneous"): "Fused",
}
MODE_MACRO = {"fwd": "Fwd", "fwd_bwd": "Train"}
DTYPE_MACRO = {"fp32": "FpThirtyTwo", "fp16": "FpSixteen", "bf16": "BfSixteen"}
METRICS = {"speedup": "latency_ms_mean", "memory": "peak_mem_mib"}

PREAMBLE = ("% Generated by scripts/make_tables.py -- do not edit by hand.\n"
            "% Regenerate with:  python make_tables.py --bench ... --correctness ...\n")


def _fmt(v: float, nd: int = 2) -> str:
    if v is None or (isinstance(v, float) and math.isnan(v)):
        return r"\textemdash"
    return f"{v:.{nd}f}"


def geomean(xs: list[float]) -> float:
    xs = [x for x in xs if x and not math.isnan(x) and x > 0]
    if not xs:
        return float("nan")
    return math.exp(sum(math.log(x) for x in xs) / len(xs))


def kernel_sizes(bench: dict) -> tuple[int, int]:
    """(homogeneous k, drop-in k) as recorded by bench.py."""
    a = bench.get("args", {})
    return (int(a.get("kernel_size", 5)),
            int(a.get("dropin_kernel_size", a.get("rf_kernel_size", 7))))


def row_labels(bench: dict) -> list[tuple[str, str, str]]:
    k, kd = kernel_sizes(bench)
    return [(m, p, t.replace("@K@", str(k)).replace("@KD@", str(kd)))
            for m, p, t in PAPER_ROWS]


# =============================================================================
# Speedup / memory tables
# =============================================================================

def build_tables(bench: dict, outdir: Path) -> None:
    rows = [r for r in bench["rows"] if r.get("ok", True)]

    # index: (protocol, mode, dtype, level, channels, spatial, method) -> row
    idx: dict[tuple, dict] = {}
    plain_at: dict[tuple, dict] = {}     # plain convs recorded once, at the first level
    for r in rows:
        key = (r["protocol"], r["mode"], r["dtype"], r["levels"],
               r["channels"], r["spatial"], r["method"])
        idx[key] = r
        if r["method"] in ("depthwise", "dense"):
            plain_at[(r["protocol"], r["mode"], r["dtype"],
                      r["channels"], r["spatial"], r["method"])] = r

    protocols = sorted({r["protocol"] for r in rows})
    modes = sorted({r["mode"] for r in rows})
    dtypes = sorted({r["dtype"] for r in rows}, key=lambda d: ["fp32", "bf16", "fp16"].index(d)
                    if d in ("fp32", "bf16", "fp16") else 9)
    levels = sorted({r["levels"] for r in rows if r["method"] == BASELINE})
    methods = [m for m in ORDER if any(r["method"] == m for r in rows)]
    k, kd = kernel_sizes(bench)

    def reference_row(protocol, mode, dtype, L, C, S):
        # The wavelet methods are measured under 'homogeneous' only; every
        # protocol takes its denominator from there.
        return (idx.get((protocol, mode, dtype, L, C, S, BASELINE))
                or idx.get(("homogeneous", mode, dtype, L, C, S, BASELINE)))

    for protocol in protocols:
        for mode in modes:
            for dtype in dtypes:
                for metric, field, caption_kind in (
                    ("speedup", "latency_ms_mean", "Speedup"),
                    ("memory", "peak_mem_mib", "Peak memory"),
                ):
                    # cell[level][method] = geometric mean over the (C, S) sweep
                    cell: dict[int, dict[str, float]] = defaultdict(dict)
                    for L in levels:
                        for method in methods:
                            ratios = []
                            for (p, mo, dt, lv, C, S, m), r in idx.items():
                                if (p, mo, dt, lv, m) != (protocol, mode, dtype, L, method):
                                    continue
                                base = reference_row(protocol, mode, dtype, L, C, S)
                                if base is None:
                                    continue
                                num, den = base[field], r[field]
                                if den and not math.isnan(den) and not math.isnan(num):
                                    ratios.append(num / den)
                            # plain convs were measured once; reuse across levels
                            if not ratios and method in ("depthwise", "dense"):
                                for (p, mo, dt, C, S, m), r in plain_at.items():
                                    if (p, mo, dt, m) != (protocol, mode, dtype, method):
                                        continue
                                    base = reference_row(protocol, mode, dtype, L, C, S)
                                    if base and r[field]:
                                        ratios.append(base[field] / r[field])
                            g = geomean(ratios)
                            # Memory reads as a fraction of the reference's
                            # footprint, matching the combined tables.
                            cell[L][method] = _invert(g) if metric == "memory" else g

                    if not any(cell[L] for L in levels):
                        continue

                    name = f"tab_{metric}_{protocol}_{mode}_{dtype}.tex"
                    _write_ratio_table(outdir / name, cell, levels, methods,
                                       protocol, mode, dtype, metric, caption_kind,
                                       k, kd)


def _write_ratio_table(path: Path, cell, levels, methods, protocol, mode,
                       dtype, metric, caption_kind, k, kd) -> None:
    proto_txt = (f"all methods at the same kernel size, $k{{=}}{k}$"
                 if protocol == "homogeneous"
                 else rf"WTConv at $k{{=}}{k}$ against plain convolutions at $k{{=}}{kd}$")
    mode_txt = "forward pass" if mode == "fwd" else "forward and backward pass"
    unit = ("mean latency; higher is better" if metric == "speedup"
            else "peak allocated memory as a fraction of the reference's; lower is better")

    lines = [PREAMBLE, r"\begin{table}[t]", r"\centering",
             rf"\caption{{{caption_kind} relative to the reference WTConv implementation "
             rf"({unit}), {mode_txt}, \texttt{{{dtype}}}. "
             rf"Protocol: {proto_txt}. Each entry is the geometric mean over the full "
             rf"sweep of channel counts and spatial resolutions.}}",
             rf"\label{{tab:{metric}-{protocol}-{mode}-{dtype}}}",
             r"\begin{tabular}{l" + "c" * len(levels) + "}", r"\toprule",
             r"\multirow{2}{*}{Method} & \multicolumn{" + str(len(levels)) +
             r"}{c}{Decomposition levels $L$} \\",
             rf"\cmidrule(lr){{2-{len(levels) + 1}}}",
             " & " + " & ".join(str(L) for L in levels) + r" \\", r"\midrule"]

    for m in methods:
        vals = [cell[L].get(m, float("nan")) for L in levels]
        row = DISPLAY.get(m, m) + " & " + " & ".join(_fmt(v) + r"$\times$" for v in vals) + r" \\"
        lines.append(row)
        if m == BASELINE:
            lines.append(r"\midrule")

    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))
    print(f"wrote {path}")


# =============================================================================
# Combined results tables (the ones the main text \inputs)
# =============================================================================

def _index(bench: dict):
    """(protocol, mode, dtype, method, level, C, S) -> row, plus the axes."""
    rows = [r for r in bench["rows"] if r.get("ok", True)]
    idx = {(r["protocol"], r["mode"], r["dtype"], r["method"], r["levels"],
            r["channels"], r["spatial"]): r for r in rows}
    axes = {
        "levels": sorted({r["levels"] for r in rows if r["method"] == BASELINE}),
        "dtypes": [d for d in ("fp32", "fp16", "bf16")
                   if any(r["dtype"] == d for r in rows)],
        "configs": sorted({(r["channels"], r["spatial"]) for r in rows}),
        "modes": sorted({r["mode"] for r in rows}),
    }
    return idx, axes


def _ratio_vs_reference(idx, axes, method, protocol, mode, dtype, L, field):
    """
    Geometric mean of reference/method over the (channels, spatial) sweep.

    The reference is always taken from the homogeneous protocol, where it runs
    at the WTConv kernel size, so every column of every combined table shares
    one denominator. Plain convolutions carry no notion of decomposition level
    and are recorded once, at the lowest level in the sweep; that measurement
    is broadcast.
    """
    plain = method in ("depthwise", "dense")
    L_num = axes["levels"][0] if plain else L
    ratios = []
    for C, S in axes["configs"]:
        base = idx.get(("homogeneous", mode, dtype, BASELINE, L, C, S))
        got = idx.get((protocol, mode, dtype, method, L_num, C, S))
        if base is None or got is None:
            continue
        num, den = base[field], got[field]
        if den and not math.isnan(den) and not math.isnan(num):
            ratios.append(num / den)
    return geomean(ratios)


def _invert(v: float) -> float:
    """Flip a reference/method ratio into method/reference, NaN-safe."""
    if v is None or math.isnan(v) or v == 0:
        return float("nan")
    return 1.0 / v


def _write_combined(path: Path, idx, axes, rows_spec, mode, field, caption, label,
                    invert: bool = False) -> None:
    """
    `invert` flips every entry into method/reference. Latency is quoted as a
    speedup (higher is better); peak memory is quoted as a fraction of the
    reference's footprint (lower is better), which is the direction the
    quantity is wanted in and the one the reporting convention states.
    """
    levels, dtypes = axes["levels"], axes["dtypes"]
    lines = [PREAMBLE, r"\begin{table}[t]", r"\centering",
             rf"\caption{{{caption}}}", rf"\label{{{label}}}",
             r"\begin{tabular}{ll" + "c" * len(levels) + "}", r"\toprule",
             r"\multirow{2}{*}{Method} & \multirow{2}{*}{Precision} & "
             rf"\multicolumn{{{len(levels)}}}{{c}}{{Decomposition levels $L$}} \\",
             rf"\cmidrule(lr){{3-{2 + len(levels)}}}",
             " & & " + " & ".join(str(L) for L in levels) + r" \\", r"\midrule"]

    for method, protocol, label_txt in rows_spec:
        for i, dtype in enumerate(dtypes):
            vals = [_ratio_vs_reference(idx, axes, method, protocol, mode,
                                        dtype, L, field) for L in levels]
            if invert:
                vals = [_invert(v) for v in vals]
            lines.append((label_txt if i == 0 else "") + " & " + DTYPE_TEX[dtype]
                         + " & " + " & ".join(_fmt(v) + r"$\times$" for v in vals)
                         + r" \\")
        lines.append(r"\addlinespace[2pt]")

    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    path.write_text("\n".join(lines))
    print(f"wrote {path}")


def _write_absolute(path: Path, idx, axes, rows_spec, C, S, L, dtype) -> None:
    """Absolute latency and peak memory at one representative configuration."""
    lines = [PREAMBLE, r"\begin{table}[t]", r"\centering",
             rf"\caption{{Absolute cost of one layer at $B{{=}}8$, $C{{=}}{C}$, "
             rf"$H{{=}}W{{=}}{S}$, $L{{=}}{L}$, \texttt{{{dtype}}}: mean latency over "
             r"50 timed iterations (CUDA events) and allocator high-water mark. "
             r"Ratios in the other tables are geometric means over the whole sweep; "
             r"this table fixes one configuration so the scale is visible.}",
             r"\label{tab:absolute}", r"\begin{tabular}{lccc}", r"\toprule",
             r"Method & Forward (ms) & Fwd+Bwd (ms) & Peak memory (MiB) \\",
             r"\midrule"]
    for method, protocol, label_txt in rows_spec:
        plain = method in ("depthwise", "dense")
        L_row = axes["levels"][0] if plain else L
        fwd = idx.get((protocol, "fwd", dtype, method, L_row, C, S))
        bwd = idx.get((protocol, "fwd_bwd", dtype, method, L_row, C, S))
        if fwd is None and bwd is None:
            continue
        lines.append(" & ".join([
            label_txt,
            _fmt(fwd["latency_ms_mean"], 3) if fwd else r"\textemdash",
            _fmt(bwd["latency_ms_mean"], 3) if bwd else r"\textemdash",
            _fmt(bwd["peak_mem_mib"], 1) if bwd else r"\textemdash",
        ]) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    path.write_text("\n".join(lines))
    print(f"wrote {path}")


def build_paper_tables(bench: dict, outdir: Path) -> None:
    idx, axes = _index(bench)
    if not axes["levels"]:
        return
    k, kd = kernel_sizes(bench)
    rows_spec = row_labels(bench)

    # The protocol note every combined caption carries. It states what the
    # drop-in protocol is and, explicitly, what it is not.
    protocol_note = (
        rf"WTConv runs at $k{{=}}{k}$ throughout, the kernel size WTConvNeXt uses. The "
        rf"plain convolutions appear twice: at the same kernel size, which isolates the "
        rf"cost of the wavelet machinery, and at $k{{=}}{kd}$, the depthwise convolution "
        rf"WTConv is proposed to replace in a ConvNeXt block. The latter is a drop-in "
        rf"comparison and not a receptive-field match: WTConv at $k{{=}}{k}$ over $L$ "
        rf"levels spans ${k}\cdot2^{{L}}$ pixels, so the plain convolutions see strictly "
        rf"less context. "
        r"Each entry is the geometric mean of per-configuration ratios over "
        r"$C\in\{32,64,128\}$ and $H{=}W\in\{128,256,512\}$ at $B{=}8$.")

    _write_combined(
        outdir / "tab_latency.tex", idx, axes, rows_spec, "fwd", "latency_ms_mean",
        r"Forward latency of every method relative to the reference WTConv "
        r"($1.00\times$; higher is faster). " + protocol_note,
        "tab:latency")

    if "fwd_bwd" in axes["modes"]:
        _write_combined(
            outdir / "tab_latency_train.tex", idx, axes, rows_spec, "fwd_bwd",
            "latency_ms_mean",
            r"Latency of a full training step (forward and backward) relative to the "
            r"reference WTConv ($1.00\times$; higher is faster), same sweep and same "
            r"conventions as \Cref{tab:latency}. The backward pass moves the same "
            r"intermediates in the opposite direction, so the reformulation applies "
            r"to it unchanged.",
            "tab:latency-train")

        _write_combined(
            outdir / "tab_memory.tex", idx, axes, rows_spec, "fwd_bwd", "peak_mem_mib",
            r"Peak allocated memory over a training step, as a fraction of what the "
            r"reference WTConv allocates ($1.00\times$; \textbf{lower is better}), same "
            r"sweep as \Cref{tab:latency}. Measured as the CUDA allocator high-water "
            r"mark, not reserved memory. Fusion removes the per-level coefficient "
            r"tensors from the autograd tape, which is where the saving comes from.",
            "tab:memory", invert=True)

    _write_combined(
        outdir / "tab_memory_inference.tex", idx, axes, rows_spec, "fwd", "peak_mem_mib",
        r"Peak allocated memory for inference (forward only, no autograd tape), as a "
        r"fraction of what the reference WTConv allocates ($1.00\times$; "
        r"\textbf{lower is better}), same sweep as \Cref{tab:latency}.",
        "tab:memory-inference", invert=True)

    # Representative configuration: middle of the sweep, in absolute units.
    dtype = axes["dtypes"][0]
    L = axes["levels"][min(2, len(axes["levels"]) - 1)]
    if (64, 256) in axes["configs"]:
        _write_absolute(outdir / "tab_absolute.tex", idx, axes, rows_spec, 64, 256, L, dtype)


# =============================================================================
# Correctness table
# =============================================================================

def build_correctness(rep: dict, outdir: Path) -> None:
    lines = [PREAMBLE, r"\begin{table}[t]", r"\centering",
             r"\caption{Numerical agreement with the reference implementation. "
             r"Entries are maximum absolute deviation over the whole tensor, at "
             r"$L$ decomposition levels, for the forward output and for the "
             r"gradients with respect to the input, the level-$L$ depthwise weight "
             r"and scale, and the base-path bias. Every parameter gradient the "
             r"layer produces is checked; the level-$L$ pair is reported as "
             r"representative. The fused kernels compute the same "
             r"multilinear map with a different association order, so the residual "
             r"is floating-point reassociation error alone.}",
             r"\label{tab:correctness}", r"\begin{tabular}{llcccccc}", r"\toprule",
             r"Backend & dtype & $L$ & forward & $\nabla_{\!X}$ & $\nabla_{\!W}$ & "
             r"$\nabla_{\!s}$ & $\nabla_{\!b}$ \\", r"\midrule"]

    last = None
    for case in rep.get("cases", []):
        res = case.get("result")
        if not res:
            continue
        be, dt, L = case["method"], case["dtype"], case["levels"]
        if last is not None and last != (be, dt):
            lines.append(r"\addlinespace[2pt]")
        last = (be, dt)

        def cell(k):
            v = res.get(k, {})
            return f"{v['max_abs']:.1e}" if "max_abs" in v else r"\textemdash"

        lines.append(" & ".join([
            DISPLAY.get(be, be).replace(r"\textbf{", "").replace("}", ""),
            rf"\texttt{{{dt}}}", str(L),
            cell("forward"), cell("grad_input"),
            cell(f"grad_wt_weight_{L - 1}"), cell(f"grad_wt_scale_{L - 1}"),
            cell("grad_base_bias"),
        ]) + r" \\")

    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    (outdir / "tab_correctness.tex").write_text("\n".join(lines))
    print(f"wrote {outdir / 'tab_correctness.tex'}")


# =============================================================================
# Environment + headline macros
# =============================================================================

def _cudnn_version(value) -> str:
    """Render torch.backends.cudnn.version() using semantic components."""
    try:
        encoded = int(value)
    except (TypeError, ValueError):
        return str(value)
    if encoded >= 10000:  # cuDNN 9 uses two digits for the minor component.
        return f"{encoded // 10000}.{(encoded % 10000) // 100}.{encoded % 100}"
    return f"{encoded // 1000}.{(encoded % 1000) // 100}.{encoded % 100}"


def build_env(bench: dict, outdir: Path, filename: str = "env.tex") -> None:
    e = bench.get("env", {})
    parts = []
    if "gpu" in e:
        parts.append(rf"{e['gpu']} (sm\_{e.get('capability', '?').replace('.', '')}, "
                     rf"{e.get('hbm_gib', '?')}\,GiB)")
    if "python" in e:
        parts.append(rf"Python~{e['python']}")
    parts.append(rf"PyTorch~{e.get('torch', '?')}")
    if "cuda" in e:
        parts.append(rf"CUDA~{e['cuda']}")
    if "cudnn" in e:
        parts.append(rf"cuDNN~{_cudnn_version(e['cudnn'])}")
    if e.get("nvidia_driver"):
        parts.append(rf"driver~{e['nvidia_driver']}")
    if e.get("nvcc"):
        parts.append(rf"nvcc~{e['nvcc']}")
    if e.get("host_compiler"):
        compiler = e["host_compiler"].replace("_", r"\_").replace("~", r"\textasciitilde{}")
        parts.append(compiler)
    if e.get("torchvision"):
        parts.append(rf"torchvision~{e['torchvision']}")
    if e.get("timm"):
        parts.append(rf"timm~{e['timm']}")
    # Trailing '%' so the file can be \input mid-sentence without adding a space.
    (outdir / filename).write_text(PREAMBLE + ", ".join(parts) + "%\n")
    print(f"wrote {outdir / filename}")


# =============================================================================
# End-to-end table
# =============================================================================

def build_endtoend(payload: dict, outdir: Path) -> None:
    rows = {(r["mode"], r["model"]): r for r in payload["rows"]}

    def table_row(mode: str, metric: str, label: str, direction: str) -> str:
        baseline = rows[(mode, "ConvNeXt-T")][metric]
        reference = rows[(mode, "WTConvNeXt-T")][metric]
        fused = rows[(mode, "WTConvNeXt-T (CUDA)")][metric]
        if metric == "throughput_images_s":
            value = lambda x: f"{x:.1f}"
        else:
            value = lambda x: f"{x:.1f}"
        return (rf" & {label} ${direction}$ & ${value(baseline)}$ & "
                rf"${value(reference)}$ (${reference / baseline:.2f}\times$) & "
                rf"${value(fused)}$ (${fused / baseline:.2f}\times$) & "
                rf"${fused / reference:.2f}\times$ \\")

    lines = [
        PREAMBLE,
        "% Generated from benchmark_throughput.py output.",
        r"\begin{table}[htpb]",
        r"\centering",
        r"\caption{End-to-end network throughput and peak allocated GPU memory, for a forward pass and for a full training step (gradient clearing, forward, backward, and SGD update). Inputs and targets are GPU-resident; data loading and host-to-device transfer are excluded.}",
        r"\label{tab:endtoend}",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{llcccc}",
        r"\toprule",
        r" & & ConvNeXt-T & \multicolumn{2}{c}{WTConvNeXt-T} & Fused / \\",
        r"\cmidrule(lr){4-5}",
        r" & & (depthwise) & reference & fused & reference \\",
        r"\midrule",
        r"\multirow{2}{*}{Inference}",
        table_row("inference", "throughput_images_s", "Throughput (img/s)", r"\uparrow"),
        table_row("inference", "peak_memory_mib", "Peak memory (MiB)", r"\downarrow"),
        r"\addlinespace[3pt]",
        r"\multirow{2}{*}{Training step}",
        table_row("train", "throughput_images_s", "Throughput (img/s)", r"\uparrow"),
        table_row("train", "peak_memory_mib", "Peak memory (MiB)", r"\downarrow"),
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        "",
    ]
    (outdir / "tab_endtoend.tex").write_text("\n".join(lines))
    print(f"wrote {outdir / 'tab_endtoend.tex'}")


# =============================================================================
# Cross-hardware validation table
# =============================================================================

def build_hardware_table(bench: dict, outdir: Path) -> None:
    """
    Compact speedup/memory summary for a second, self-contained bench JSON
    (e.g. a different GPU), in the same Quantity x Precision x Level pivot
    layout as the kernel-size ablation (tab_k3.tex), restricted to the fused
    kernel against its own reference. Reuses the same ratio machinery as the
    main combined tables so no number here is computed differently from those.
    """
    idx, axes = _index(bench)
    if not axes["levels"]:
        return
    levels = axes["levels"]
    dtypes = [d for d in ("fp32", "fp16") if d in axes["dtypes"]]
    if not dtypes:
        return

    specs = [
        ("Training-step speedup", "fwd_bwd", "latency_ms_mean", False),
        ("Inference speedup", "fwd", "latency_ms_mean", False),
        ("Peak memory, training", "fwd_bwd", "peak_mem_mib", True),
        ("Peak memory, inference", "fwd", "peak_mem_mib", True),
    ]

    lines = [PREAMBLE, r"\begin{table}[t]", r"\centering",
             r"\caption{The fused layer compared with the reference WTConv, both measured "
             r"on the second GPU (\Cref{sec:results-hardware}), $k{=}5$. Latency is reported "
             r"as speedup relative to the reference ($1.00\times$; higher is faster), and peak "
             r"allocated memory as a fraction of the reference ($1.00\times$; lower is better).}",
             r"\label{tab:hardware}",
             r"\begin{tabular}{ll" + "c" * len(levels) + "}", r"\toprule",
             r"\multirow{2}{*}{Quantity} & \multirow{2}{*}{Precision} & "
             rf"\multicolumn{{{len(levels)}}}{{c}}{{Decomposition levels $L$}} \\",
             rf"\cmidrule(lr){{3-{2 + len(levels)}}}",
             " & & " + " & ".join(str(L) for L in levels) + r" \\", r"\midrule"]

    for label, mode, field, invert in specs:
        if mode not in axes["modes"]:
            continue
        for i, dtype in enumerate(dtypes):
            vals = [_ratio_vs_reference(idx, axes, "fused_cuda", "homogeneous", mode,
                                        dtype, L, field) for L in levels]
            if invert:
                vals = [_invert(v) for v in vals]
            lines.append((label if i == 0 else "") + " & " + DTYPE_TEX[dtype] + " & "
                         + " & ".join(_fmt(v) + r"$\times$" for v in vals) + r" \\")
        lines.append(r"\addlinespace[2pt]")

    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    (outdir / "tab_hardware.tex").write_text("\n".join(lines))
    print(f"wrote {outdir / 'tab_hardware.tex'}")


def _percentile(xs: list[float], q: float) -> float:
    if not xs:
        return float("nan")
    s = sorted(xs)
    i = min(len(s) - 1, max(0, int(round(q * (len(s) - 1)))))
    return s[i]


def build_macros(bench: dict, outdir: Path) -> None:
    """
    Every measured number the prose quotes, as a macro.

    The manuscript must not contain a hand-typed measurement: if a ratio appears
    in a sentence it appears as \\SomeMacro, defined here from the same JSON the
    tables are built from. Ranges are emitted as Min/Max over the level sweep,
    plus MinInv/MaxInv for sentences phrased as a fraction rather than a factor.
    """
    idx, axes = _index(bench)
    k, kd = kernel_sizes(bench)
    defs: dict[str, str] = {}

    for metric, field in METRICS.items():
        for (method, protocol), rowname in ROW_MACRO.items():
            for mode, modename in MODE_MACRO.items():
                if mode not in axes["modes"]:
                    continue
                for dtype, dtname in DTYPE_MACRO.items():
                    if dtype not in axes["dtypes"]:
                        continue
                    vals = [_ratio_vs_reference(idx, axes, method, protocol, mode,
                                                dtype, L, field)
                            for L in axes["levels"]]
                    vals = [v for v in vals if v and not math.isnan(v)]
                    if not vals:
                        continue
                    stem = f"{metric.capitalize()}{rowname}{modename}{dtname}"
                    lo, hi = min(vals), max(vals)
                    defs[stem + "Min"] = _fmt(lo)
                    defs[stem + "Max"] = _fmt(hi)
                    defs[stem + "MinInv"] = _fmt(1.0 / hi)
                    defs[stem + "MaxInv"] = _fmt(1.0 / lo)

    # --- sweep description ---------------------------------------------------
    rows = [r for r in bench["rows"] if r.get("ok", True)]
    spreads = [(r["latency_ms_p90"] - r["latency_ms_p10"]) / r["latency_ms_mean"]
               for r in rows
               if r.get("latency_ms_mean") and not math.isnan(r["latency_ms_mean"])]
    defs["NumMeasurements"] = str(len(rows))
    defs["DispersionMedian"] = _fmt(100 * _percentile(spreads, 0.50), 1)
    defs["DispersionPNinetyFive"] = _fmt(100 * _percentile(spreads, 0.95), 1)
    defs["KernelSize"] = str(k)
    defs["DropinKernelSize"] = str(kd)
    defs["NumLevels"] = str(max(axes["levels"])) if axes["levels"] else "0"

    lines = [PREAMBLE]
    for name, v in sorted(defs.items()):
        lines.append(rf"\newcommand{{\{name}}}{{{v}}}")
    (outdir / "macros.tex").write_text("\n".join(lines) + "\n")
    print(f"wrote {outdir / 'macros.tex'} ({len(defs)} macros)")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--bench", type=Path, action="append", default=None,
                   help="benchmark JSON; may be given more than once")
    p.add_argument("--correctness", type=Path)
    p.add_argument("--bench-hardware", type=Path, default=None,
                   help="optional second self-contained bench JSON (e.g. a different GPU) "
                        "for the cross-hardware validation table (tab_hardware.tex)")
    p.add_argument("--endtoend", type=Path, action="append", default=None,
                   help="end-to-end benchmark JSON; repeat for inference and training files")
    p.add_argument("--outdir", type=Path, default=Path(__file__).resolve().parent.parent / "results")
    args = p.parse_args()
    args.outdir.mkdir(parents=True, exist_ok=True)

    merged = {"env": {}, "args": {}, "rows": []}
    for b in (args.bench or []):
        data = json.loads(b.read_text())
        merged["rows"].extend(data["rows"])
        merged["env"] = merged["env"] or data.get("env", {})
        merged["args"] = merged["args"] or data.get("args", {})
    if merged["rows"]:
        build_paper_tables(merged, args.outdir)
        # Per-(protocol, mode, dtype) renderings of the same measurements. The
        # manuscript does not \input these; they live one level down so that
        # results/ contains only what the paper actually uses.
        per_config = args.outdir / "per_config"
        per_config.mkdir(parents=True, exist_ok=True)
        build_tables(merged, per_config)
        build_env(merged, args.outdir)
        build_macros(merged, args.outdir)
    if args.correctness and args.correctness.exists():
        build_correctness(json.loads(args.correctness.read_text()), args.outdir)
    if args.bench_hardware and args.bench_hardware.exists():
        hw = json.loads(args.bench_hardware.read_text())
        build_hardware_table(hw, args.outdir)
        build_env(hw, args.outdir, filename="env_hardware.tex")
    if args.endtoend:
        endtoend = {"environment": {}, "protocol": {}, "rows": []}
        for path in args.endtoend:
            if not path.exists():
                continue
            run = json.loads(path.read_text())
            endtoend["environment"] = endtoend["environment"] or run.get("environment", {})
            endtoend["protocol"] = endtoend["protocol"] or run.get("protocol", {})
            endtoend["rows"].extend(run["rows"])
        if endtoend["rows"]:
            build_endtoend(endtoend, args.outdir)


if __name__ == "__main__":
    main()
