#!/usr/bin/env python3
"""
Turn raw benchmark/correctness JSON into the LaTeX fragments the paper
\\inputs. Running this is the only way numbers enter the manuscript, so the
tables cannot drift from the measurements.

Outputs (into --outdir, default ../results):
    tab_speedup_<protocol>_<mode>_<dtype>.tex
    tab_memory_<protocol>_<mode>_<dtype>.tex
    tab_correctness.tex
    env.tex                 hardware/software line for the appendix
    macros.tex              \\newcommand definitions for headline numbers

Usage
-----
    python make_tables.py --bench ../results/bench_cuda.json \\
                          --correctness ../results/correctness.json
"""

from __future__ import annotations

import argparse
import json
import math
from collections import defaultdict
from pathlib import Path

BASELINE = "reference"          # denominator for every speedup ratio
DISPLAY = {
    "depthwise": r"Depthwise",
    "dense": r"Dense",
    "reference": r"WTConv~\citep{finder2024wavelet}",
    "fused_cuda": r"\textbf{Fused (CUDA)}",
    "fused_triton": r"\textbf{Fused (Triton)}",
}
ORDER = ["depthwise", "dense", "reference", "fused_cuda", "fused_triton"]

PREAMBLE = ("% Generated by scripts/make_tables.py -- do not edit by hand.\n"
            "% Regenerate with:  python make_tables.py --bench ... --correctness ...\n")


def _fmt(v: float, nd: int = 2) -> str:
    if v is None or (isinstance(v, float) and math.isnan(v)):
        return r"\textemdash"
    return f"{v:.{nd}f}"


def geomean(xs: list[float]) -> float:
    xs = [x for x in xs if x and not math.isnan(x) and x > 0]
    if not xs:
        return float("nan")
    return math.exp(sum(math.log(x) for x in xs) / len(xs))


# =============================================================================
# Speedup / memory tables
# =============================================================================

def build_tables(bench: dict, outdir: Path) -> dict:
    rows = [r for r in bench["rows"] if r.get("ok", True)]
    headline: dict[str, float] = {}

    # index: (protocol, mode, dtype, level, channels, spatial, method) -> row
    idx: dict[tuple, dict] = {}
    plain_at: dict[tuple, dict] = {}     # plain convs recorded once, at the first level
    for r in rows:
        key = (r["protocol"], r["mode"], r["dtype"], r["levels"],
               r["channels"], r["spatial"], r["method"])
        idx[key] = r
        if r["method"] in ("depthwise", "dense"):
            plain_at[(r["protocol"], r["mode"], r["dtype"],
                      r["channels"], r["spatial"], r["method"])] = r

    protocols = sorted({r["protocol"] for r in rows})
    modes = sorted({r["mode"] for r in rows})
    dtypes = sorted({r["dtype"] for r in rows}, key=lambda d: ["fp32", "bf16", "fp16"].index(d)
                    if d in ("fp32", "bf16", "fp16") else 9)
    levels = sorted({r["levels"] for r in rows})
    methods = [m for m in ORDER if any(r["method"] == m for r in rows)]

    for protocol in protocols:
        for mode in modes:
            for dtype in dtypes:
                for metric, field, caption_kind in (
                    ("speedup", "latency_ms_mean", "Speedup"),
                    ("memory", "peak_mem_mib", "Peak-memory reduction"),
                ):
                    # cell[level][method] = geometric mean over the (C, S) sweep
                    cell: dict[int, dict[str, float]] = defaultdict(dict)
                    for L in levels:
                        for method in methods:
                            ratios = []
                            for (p, mo, dt, lv, C, S, m), r in idx.items():
                                if (p, mo, dt, lv, m) != (protocol, mode, dtype, L, method):
                                    continue
                                base = idx.get((protocol, mode, dtype, L, C, S, BASELINE))
                                if base is None:
                                    continue
                                num, den = base[field], r[field]
                                if den and not math.isnan(den) and not math.isnan(num):
                                    ratios.append(num / den)
                            # plain convs were measured once; reuse across levels
                            if not ratios and method in ("depthwise", "dense"):
                                for (p, mo, dt, C, S, m), r in plain_at.items():
                                    if (p, mo, dt, m) != (protocol, mode, dtype, method):
                                        continue
                                    base = idx.get((protocol, mode, dtype, L, C, S, BASELINE))
                                    if base and r[field]:
                                        ratios.append(base[field] / r[field])
                            cell[L][method] = geomean(ratios)

                    if not any(cell[L] for L in levels):
                        continue

                    name = f"tab_{metric}_{protocol}_{mode}_{dtype}.tex"
                    _write_ratio_table(outdir / name, cell, levels, methods,
                                       protocol, mode, dtype, metric, caption_kind)

                    for L in levels:
                        for m in ("fused_cuda", "fused_triton"):
                            v = cell[L].get(m)
                            if v and not math.isnan(v):
                                headline[f"{metric}.{protocol}.{mode}.{dtype}.L{L}.{m}"] = v
    return headline


def _write_ratio_table(path: Path, cell, levels, methods, protocol, mode,
                       dtype, metric, caption_kind) -> None:
    proto_txt = ("all methods at the same kernel size"
                 if protocol == "homogeneous"
                 else r"WTConv at $k{=}3$ against plain convolutions at $k{=}7$")
    mode_txt = "forward pass" if mode == "fwd" else "forward and backward pass"
    unit = ("mean latency" if metric == "speedup" else "peak allocated memory")

    lines = [PREAMBLE, r"\begin{table}[t]", r"\centering",
             rf"\caption{{{caption_kind} relative to the reference WTConv implementation "
             rf"({unit}; higher is better), {mode_txt}, \texttt{{{dtype}}}. "
             rf"Protocol: {proto_txt}. Each entry is the geometric mean over the full "
             rf"sweep of channel counts and spatial resolutions.}}",
             rf"\label{{tab:{metric}-{protocol}-{mode}-{dtype}}}",
             r"\begin{tabular}{l" + "c" * len(levels) + "}", r"\toprule",
             r"\multirow{2}{*}{Method} & \multicolumn{" + str(len(levels)) +
             r"}{c}{Decomposition levels $L$} \\",
             rf"\cmidrule(lr){{2-{len(levels) + 1}}}",
             " & " + " & ".join(str(L) for L in levels) + r" \\", r"\midrule"]

    for m in methods:
        vals = [cell[L].get(m, float("nan")) for L in levels]
        row = DISPLAY.get(m, m) + " & " + " & ".join(_fmt(v) + r"$\times$" for v in vals) + r" \\"
        if m == BASELINE:
            lines.append(row)
            lines.append(r"\midrule")
        else:
            lines.append(row)

    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))
    print(f"wrote {path}")


# =============================================================================
# Correctness table
# =============================================================================

def build_correctness(rep: dict, outdir: Path) -> None:
    lines = [PREAMBLE, r"\begin{table}[t]", r"\centering",
             r"\caption{Numerical agreement with the reference implementation. "
             r"Entries are maximum absolute deviation over the whole tensor, at "
             r"$L$ decomposition levels, for the forward output and for every "
             r"gradient the layer produces. The fused kernels compute the same "
             r"multilinear map with a different association order, so the residual "
             r"is floating-point reassociation error alone.}",
             r"\label{tab:correctness}", r"\begin{tabular}{llccccc}", r"\toprule",
             r"Backend & dtype & $L$ & forward & $\nabla_{\!X}$ & $\nabla_{\!W}$ & "
             r"$\nabla_{\!s}$ \\", r"\midrule"]

    last = None
    for case in rep.get("cases", []):
        res = case.get("result")
        if not res:
            continue
        be, dt, L = case["method"], case["dtype"], case["levels"]
        if last is not None and last != (be, dt):
            lines.append(r"\addlinespace[2pt]")
        last = (be, dt)

        def cell(k):
            v = res.get(k, {})
            return f"{v['max_abs']:.1e}" if "max_abs" in v else r"\textemdash"

        lines.append(" & ".join([
            DISPLAY.get(be, be).replace(r"\textbf{", "").replace("}", ""),
            rf"\texttt{{{dt}}}", str(L),
            cell("forward"), cell("grad_input"),
            cell(f"grad_wt_weight_{L - 1}"), cell(f"grad_wt_scale_{L - 1}"),
        ]) + r" \\")

    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    (outdir / "tab_correctness.tex").write_text("\n".join(lines))
    print(f"wrote {outdir / 'tab_correctness.tex'}")


# =============================================================================
# Environment + headline macros
# =============================================================================

def build_env(bench: dict, outdir: Path) -> None:
    e = bench.get("env", {})
    parts = []
    if "gpu" in e:
        parts.append(rf"{e['gpu']} (sm\_{e.get('capability', '?').replace('.', '')}, "
                     rf"{e.get('hbm_gib', '?')}\,GiB)")
    parts.append(rf"PyTorch~{e.get('torch', '?')}")
    if "cuda" in e:
        parts.append(rf"CUDA~{e['cuda']}")
    if "cudnn" in e:
        parts.append(rf"cuDNN~{e['cudnn']}")
    if "triton" in e:
        parts.append(rf"Triton~{e['triton']}")
    (outdir / "env.tex").write_text(PREAMBLE + ", ".join(parts) + "\n")
    print(f"wrote {outdir / 'env.tex'}")


def build_macros(headline: dict, outdir: Path) -> None:
    """Headline numbers quoted in the abstract and introduction."""
    def best(pred) -> float:
        vs = [v for k, v in headline.items() if pred(k)]
        return max(vs) if vs else float("nan")

    defs = {
        "SpeedupCudaFPTwoMax": best(lambda k: k.startswith("speedup.homogeneous.fwd.fp32")
                                    and k.endswith("fused_cuda")),
        "SpeedupTritonFPTwoMax": best(lambda k: k.startswith("speedup.homogeneous.fwd.fp32")
                                      and k.endswith("fused_triton")),
        "SpeedupCudaFPOneMax": best(lambda k: k.startswith("speedup.homogeneous.fwd.fp16")
                                    and k.endswith("fused_cuda")),
        "SpeedupTritonFPOneMax": best(lambda k: k.startswith("speedup.homogeneous.fwd.fp16")
                                      and k.endswith("fused_triton")),
        "MemoryCudaMax": best(lambda k: k.startswith("memory.homogeneous.fwd.fp32")
                              and k.endswith("fused_cuda")),
    }
    lines = [PREAMBLE]
    for k, v in defs.items():
        lines.append(rf"\newcommand{{\{k}}}{{{_fmt(v)}}}")
    (outdir / "macros.tex").write_text("\n".join(lines) + "\n")
    print(f"wrote {outdir / 'macros.tex'}")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--bench", type=Path, action="append", default=None,
                   help="benchmark JSON; may be given more than once")
    p.add_argument("--correctness", type=Path)
    p.add_argument("--outdir", type=Path, default=Path(__file__).resolve().parent.parent / "results")
    args = p.parse_args()
    args.outdir.mkdir(parents=True, exist_ok=True)

    headline: dict[str, float] = {}
    merged = {"env": {}, "rows": []}
    for b in (args.bench or []):
        data = json.loads(b.read_text())
        merged["rows"].extend(data["rows"])
        merged["env"] = merged["env"] or data.get("env", {})
    if merged["rows"]:
        headline = build_tables(merged, args.outdir)
        build_env(merged, args.outdir)
        build_macros(headline, args.outdir)
    if args.correctness and args.correctness.exists():
        build_correctness(json.loads(args.correctness.read_text()), args.outdir)


if __name__ == "__main__":
    main()
