#!/usr/bin/env python3
"""
Turn raw benchmark/correctness JSON into the LaTeX fragments the paper
\\inputs. Running this is the only way numbers enter the manuscript, so the
tables cannot drift from the measurements.

Outputs (into --outdir, default ../results):
    tab_speedup_<protocol>_<mode>_<dtype>.tex
    tab_memory_<protocol>_<mode>_<dtype>.tex
    tab_correctness.tex
    env.tex                 hardware/software line for the appendix
    macros.tex              \\newcommand definitions for headline numbers

Usage
-----
    python make_tables.py --bench ../results/bench_cuda.json \\
                          --correctness ../results/correctness.json
"""

from __future__ import annotations

import argparse
import json
import math
from collections import defaultdict
from pathlib import Path

BASELINE = "reference"          # denominator for every speedup ratio
DISPLAY = {
    "depthwise": r"Depthwise",
    "dense": r"Dense",
    "reference": r"WTConv~\citep{finder2024wavelet}",
    "fused_cuda": r"\textbf{Fused (CUDA)}",
    "fused_triton": r"\textbf{Fused (Triton)}",
}
ORDER = ["depthwise", "dense", "reference", "fused_cuda", "fused_triton"]

# Rows of the combined results tables: (method, protocol, label). The plain
# convolutions appear twice, once per protocol, so that a single table carries
# both the matched-kernel-size and the matched-receptive-field baselines.
PAPER_ROWS = [
    ("depthwise", "homogeneous", r"Depthwise conv, $k{=}3$"),
    ("dense", "homogeneous", r"Dense conv, $k{=}3$"),
    ("depthwise", "rfmatch", r"Depthwise conv, $k{=}7$"),
    ("dense", "rfmatch", r"Dense conv, $k{=}7$"),
    ("reference", "homogeneous", r"WTConv, reference"),
    ("fused_cuda", "homogeneous", r"WTConv, \textbf{fused}"),
]
DTYPE_TEX = {"fp32": r"\texttt{fp32}", "fp16": r"\texttt{fp16}", "bf16": r"\texttt{bf16}"}

PREAMBLE = ("% Generated by scripts/make_tables.py -- do not edit by hand.\n"
            "% Regenerate with:  python make_tables.py --bench ... --correctness ...\n")


def _fmt(v: float, nd: int = 2) -> str:
    if v is None or (isinstance(v, float) and math.isnan(v)):
        return r"\textemdash"
    return f"{v:.{nd}f}"


def geomean(xs: list[float]) -> float:
    xs = [x for x in xs if x and not math.isnan(x) and x > 0]
    if not xs:
        return float("nan")
    return math.exp(sum(math.log(x) for x in xs) / len(xs))


# =============================================================================
# Speedup / memory tables
# =============================================================================

def build_tables(bench: dict, outdir: Path) -> dict:
    rows = [r for r in bench["rows"] if r.get("ok", True)]
    headline: dict[str, float] = {}

    # index: (protocol, mode, dtype, level, channels, spatial, method) -> row
    idx: dict[tuple, dict] = {}
    plain_at: dict[tuple, dict] = {}     # plain convs recorded once, at the first level
    for r in rows:
        key = (r["protocol"], r["mode"], r["dtype"], r["levels"],
               r["channels"], r["spatial"], r["method"])
        idx[key] = r
        if r["method"] in ("depthwise", "dense"):
            plain_at[(r["protocol"], r["mode"], r["dtype"],
                      r["channels"], r["spatial"], r["method"])] = r

    protocols = sorted({r["protocol"] for r in rows})
    modes = sorted({r["mode"] for r in rows})
    dtypes = sorted({r["dtype"] for r in rows}, key=lambda d: ["fp32", "bf16", "fp16"].index(d)
                    if d in ("fp32", "bf16", "fp16") else 9)
    levels = sorted({r["levels"] for r in rows})
    methods = [m for m in ORDER if any(r["method"] == m for r in rows)]

    for protocol in protocols:
        for mode in modes:
            for dtype in dtypes:
                for metric, field, caption_kind in (
                    ("speedup", "latency_ms_mean", "Speedup"),
                    ("memory", "peak_mem_mib", "Peak-memory reduction"),
                ):
                    # cell[level][method] = geometric mean over the (C, S) sweep
                    cell: dict[int, dict[str, float]] = defaultdict(dict)
                    for L in levels:
                        for method in methods:
                            ratios = []
                            for (p, mo, dt, lv, C, S, m), r in idx.items():
                                if (p, mo, dt, lv, m) != (protocol, mode, dtype, L, method):
                                    continue
                                base = idx.get((protocol, mode, dtype, L, C, S, BASELINE))
                                if base is None:
                                    continue
                                num, den = base[field], r[field]
                                if den and not math.isnan(den) and not math.isnan(num):
                                    ratios.append(num / den)
                            # plain convs were measured once; reuse across levels
                            if not ratios and method in ("depthwise", "dense"):
                                for (p, mo, dt, C, S, m), r in plain_at.items():
                                    if (p, mo, dt, m) != (protocol, mode, dtype, method):
                                        continue
                                    base = idx.get((protocol, mode, dtype, L, C, S, BASELINE))
                                    if base and r[field]:
                                        ratios.append(base[field] / r[field])
                            cell[L][method] = geomean(ratios)

                    if not any(cell[L] for L in levels):
                        continue

                    name = f"tab_{metric}_{protocol}_{mode}_{dtype}.tex"
                    _write_ratio_table(outdir / name, cell, levels, methods,
                                       protocol, mode, dtype, metric, caption_kind)

                    for L in levels:
                        for m in ("fused_cuda", "fused_triton"):
                            v = cell[L].get(m)
                            if v and not math.isnan(v):
                                headline[f"{metric}.{protocol}.{mode}.{dtype}.L{L}.{m}"] = v
    return headline


def _write_ratio_table(path: Path, cell, levels, methods, protocol, mode,
                       dtype, metric, caption_kind) -> None:
    proto_txt = ("all methods at the same kernel size"
                 if protocol == "homogeneous"
                 else r"WTConv at $k{=}3$ against plain convolutions at $k{=}7$")
    mode_txt = "forward pass" if mode == "fwd" else "forward and backward pass"
    unit = ("mean latency" if metric == "speedup" else "peak allocated memory")

    lines = [PREAMBLE, r"\begin{table}[t]", r"\centering",
             rf"\caption{{{caption_kind} relative to the reference WTConv implementation "
             rf"({unit}; higher is better), {mode_txt}, \texttt{{{dtype}}}. "
             rf"Protocol: {proto_txt}. Each entry is the geometric mean over the full "
             rf"sweep of channel counts and spatial resolutions.}}",
             rf"\label{{tab:{metric}-{protocol}-{mode}-{dtype}}}",
             r"\begin{tabular}{l" + "c" * len(levels) + "}", r"\toprule",
             r"\multirow{2}{*}{Method} & \multicolumn{" + str(len(levels)) +
             r"}{c}{Decomposition levels $L$} \\",
             rf"\cmidrule(lr){{2-{len(levels) + 1}}}",
             " & " + " & ".join(str(L) for L in levels) + r" \\", r"\midrule"]

    for m in methods:
        vals = [cell[L].get(m, float("nan")) for L in levels]
        row = DISPLAY.get(m, m) + " & " + " & ".join(_fmt(v) + r"$\times$" for v in vals) + r" \\"
        if m == BASELINE:
            lines.append(row)
            lines.append(r"\midrule")
        else:
            lines.append(row)

    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))
    print(f"wrote {path}")


# =============================================================================
# Combined results tables (the ones the main text \inputs)
# =============================================================================

def _index(bench: dict):
    """(protocol, mode, dtype, method, level, C, S) -> row, plus the axes."""
    rows = [r for r in bench["rows"] if r.get("ok", True)]
    idx = {(r["protocol"], r["mode"], r["dtype"], r["method"], r["levels"],
            r["channels"], r["spatial"]): r for r in rows}
    axes = {
        "levels": sorted({r["levels"] for r in rows if r["method"] == BASELINE}),
        "dtypes": [d for d in ("fp32", "fp16", "bf16")
                   if any(r["dtype"] == d for r in rows)],
        "configs": sorted({(r["channels"], r["spatial"]) for r in rows}),
        "modes": sorted({r["mode"] for r in rows}),
    }
    return idx, axes


def _ratio_vs_reference(idx, axes, method, protocol, mode, dtype, L, field):
    """
    Geometric mean of reference/method over the (channels, spatial) sweep.

    The reference is always taken from the homogeneous protocol, where it runs
    at k=3, so every column of every combined table shares one denominator.
    Plain convolutions carry no notion of decomposition level and are recorded
    once, at the lowest level in the sweep; that measurement is broadcast.
    """
    plain = method in ("depthwise", "dense")
    L_num = axes["levels"][0] if plain else L
    ratios = []
    for C, S in axes["configs"]:
        base = idx.get(("homogeneous", mode, dtype, BASELINE, L, C, S))
        got = idx.get((protocol, mode, dtype, method, L_num, C, S))
        if base is None or got is None:
            continue
        num, den = base[field], got[field]
        if den and not math.isnan(den) and not math.isnan(num):
            ratios.append(num / den)
    return geomean(ratios)


def _write_combined(path: Path, idx, axes, mode, field, caption, label) -> None:
    levels, dtypes = axes["levels"], axes["dtypes"]
    lines = [PREAMBLE, r"\begin{table}[t]", r"\centering",
             rf"\caption{{{caption}}}", rf"\label{{{label}}}",
             r"\begin{tabular}{ll" + "c" * len(levels) + "}", r"\toprule",
             r"\multirow{2}{*}{Method} & \multirow{2}{*}{Precision} & "
             rf"\multicolumn{{{len(levels)}}}{{c}}{{Decomposition levels $L$}} \\",
             rf"\cmidrule(lr){{3-{2 + len(levels)}}}",
             " & & " + " & ".join(str(L) for L in levels) + r" \\", r"\midrule"]

    for method, protocol, label_txt in PAPER_ROWS:
        for i, dtype in enumerate(dtypes):
            vals = [_ratio_vs_reference(idx, axes, method, protocol, mode,
                                        dtype, L, field) for L in levels]
            lines.append((label_txt if i == 0 else "") + " & " + DTYPE_TEX[dtype]
                         + " & " + " & ".join(_fmt(v) + r"$\times$" for v in vals)
                         + r" \\")
        lines.append(r"\addlinespace[2pt]")

    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    path.write_text("\n".join(lines))
    print(f"wrote {path}")


def _write_absolute(path: Path, idx, axes, C, S, L, dtype) -> None:
    """Absolute latency and peak memory at one representative configuration."""
    lines = [PREAMBLE, r"\begin{table}[t]", r"\centering",
             rf"\caption{{Absolute cost of one layer at $B{{=}}8$, $C{{=}}{C}$, "
             rf"$H{{=}}W{{=}}{S}$, $L{{=}}{L}$, \texttt{{{dtype}}}: mean latency over "
             r"50 timed iterations (CUDA events) and allocator high-water mark. "
             r"Ratios in the other tables are geometric means over the whole sweep; "
             r"this table fixes one configuration so the scale is visible.}",
             r"\label{tab:absolute}", r"\begin{tabular}{lccc}", r"\toprule",
             r"Method & Forward (ms) & Fwd+Bwd (ms) & Peak memory (MiB) \\",
             r"\midrule"]
    for method, protocol, label_txt in PAPER_ROWS:
        plain = method in ("depthwise", "dense")
        L_row = axes["levels"][0] if plain else L
        fwd = idx.get((protocol, "fwd", dtype, method, L_row, C, S))
        bwd = idx.get((protocol, "fwd_bwd", dtype, method, L_row, C, S))
        if fwd is None and bwd is None:
            continue
        lines.append(" & ".join([
            label_txt,
            _fmt(fwd["latency_ms_mean"], 3) if fwd else r"\textemdash",
            _fmt(bwd["latency_ms_mean"], 3) if bwd else r"\textemdash",
            _fmt(bwd["peak_mem_mib"], 1) if bwd else r"\textemdash",
        ]) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    path.write_text("\n".join(lines))
    print(f"wrote {path}")


def build_paper_tables(bench: dict, outdir: Path) -> None:
    idx, axes = _index(bench)
    if not axes["levels"]:
        return

    _write_combined(
        outdir / "tab_latency.tex", idx, axes, "fwd", "latency_ms_mean",
        r"Forward latency of every method relative to the reference WTConv "
        r"($1.00\times$; higher is faster). WTConv runs at $k{=}3$ throughout; the "
        r"plain convolutions appear both at the same kernel size and at $k{=}7$, "
        r"which is the receptive-field-matched comparison a practitioner faces. "
        r"Each entry is the geometric mean of per-configuration ratios over "
        r"$C\in\{32,64,128\}$ and $H{=}W\in\{128,256,512\}$ at $B{=}8$.",
        "tab:latency")

    if "fwd_bwd" in axes["modes"]:
        _write_combined(
            outdir / "tab_latency_train.tex", idx, axes, "fwd_bwd", "latency_ms_mean",
            r"Latency of a full training step (forward and backward) relative to the "
            r"reference WTConv ($1.00\times$; higher is faster), same sweep and same "
            r"conventions as \Cref{tab:latency}. The backward pass moves the same "
            r"intermediates in the opposite direction, so the reformulation applies "
            r"to it unchanged.",
            "tab:latency-train")

        _write_combined(
            outdir / "tab_memory.tex", idx, axes, "fwd_bwd", "peak_mem_mib",
            r"Peak allocated memory over a training step relative to the reference "
            r"WTConv ($1.00\times$; higher means the method needs less memory), same "
            r"sweep as \Cref{tab:latency}. Measured as the CUDA allocator high-water "
            r"mark, not reserved memory. Fusion removes the per-level coefficient "
            r"tensors from the autograd tape, which is where the saving comes from.",
            "tab:memory")

    _write_combined(
        outdir / "tab_memory_inference.tex", idx, axes, "fwd", "peak_mem_mib",
        r"Peak allocated memory for inference (forward only, no autograd tape) "
        r"relative to the reference WTConv ($1.00\times$; higher means less memory), "
        r"same sweep as \Cref{tab:latency}.",
        "tab:memory-inference")

    # Representative configuration: middle of the sweep, in absolute units.
    dtype = axes["dtypes"][0]
    L = axes["levels"][min(2, len(axes["levels"]) - 1)]
    if (64, 256) in axes["configs"]:
        _write_absolute(outdir / "tab_absolute.tex", idx, axes, 64, 256, L, dtype)


# =============================================================================
# Correctness table
# =============================================================================

def build_correctness(rep: dict, outdir: Path) -> None:
    lines = [PREAMBLE, r"\begin{table}[t]", r"\centering",
             r"\caption{Numerical agreement with the reference implementation. "
             r"Entries are maximum absolute deviation over the whole tensor, at "
             r"$L$ decomposition levels, for the forward output and for every "
             r"gradient the layer produces. The fused kernels compute the same "
             r"multilinear map with a different association order, so the residual "
             r"is floating-point reassociation error alone.}",
             r"\label{tab:correctness}", r"\begin{tabular}{llccccc}", r"\toprule",
             r"Backend & dtype & $L$ & forward & $\nabla_{\!X}$ & $\nabla_{\!W}$ & "
             r"$\nabla_{\!s}$ \\", r"\midrule"]

    last = None
    for case in rep.get("cases", []):
        res = case.get("result")
        if not res:
            continue
        be, dt, L = case["method"], case["dtype"], case["levels"]
        if last is not None and last != (be, dt):
            lines.append(r"\addlinespace[2pt]")
        last = (be, dt)

        def cell(k):
            v = res.get(k, {})
            return f"{v['max_abs']:.1e}" if "max_abs" in v else r"\textemdash"

        lines.append(" & ".join([
            DISPLAY.get(be, be).replace(r"\textbf{", "").replace("}", ""),
            rf"\texttt{{{dt}}}", str(L),
            cell("forward"), cell("grad_input"),
            cell(f"grad_wt_weight_{L - 1}"), cell(f"grad_wt_scale_{L - 1}"),
        ]) + r" \\")

    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    (outdir / "tab_correctness.tex").write_text("\n".join(lines))
    print(f"wrote {outdir / 'tab_correctness.tex'}")


# =============================================================================
# Environment + headline macros
# =============================================================================

def build_env(bench: dict, outdir: Path) -> None:
    e = bench.get("env", {})
    parts = []
    if "gpu" in e:
        parts.append(rf"{e['gpu']} (sm\_{e.get('capability', '?').replace('.', '')}, "
                     rf"{e.get('hbm_gib', '?')}\,GiB)")
    parts.append(rf"PyTorch~{e.get('torch', '?')}")
    if "cuda" in e:
        parts.append(rf"CUDA~{e['cuda']}")
    if "cudnn" in e:
        parts.append(rf"cuDNN~{e['cudnn']}")
    if "triton" in e:
        parts.append(rf"Triton~{e['triton']}")
    # Trailing '%' so the file can be \input mid-sentence without adding a space.
    (outdir / "env.tex").write_text(PREAMBLE + ", ".join(parts) + "%\n")
    print(f"wrote {outdir / 'env.tex'}")


def build_macros(headline: dict, outdir: Path) -> None:
    """Headline numbers quoted in the abstract and introduction."""
    def best(pred) -> float:
        vs = [v for k, v in headline.items() if pred(k)]
        return max(vs) if vs else float("nan")

    defs = {
        "SpeedupCudaFPTwoMax": best(lambda k: k.startswith("speedup.homogeneous.fwd.fp32")
                                    and k.endswith("fused_cuda")),
        "SpeedupTritonFPTwoMax": best(lambda k: k.startswith("speedup.homogeneous.fwd.fp32")
                                      and k.endswith("fused_triton")),
        "SpeedupCudaFPOneMax": best(lambda k: k.startswith("speedup.homogeneous.fwd.fp16")
                                    and k.endswith("fused_cuda")),
        "SpeedupTritonFPOneMax": best(lambda k: k.startswith("speedup.homogeneous.fwd.fp16")
                                      and k.endswith("fused_triton")),
        "MemoryCudaMax": best(lambda k: k.startswith("memory.homogeneous.fwd.fp32")
                              and k.endswith("fused_cuda")),
    }
    lines = [PREAMBLE]
    for k, v in defs.items():
        lines.append(rf"\newcommand{{\{k}}}{{{_fmt(v)}}}")
    (outdir / "macros.tex").write_text("\n".join(lines) + "\n")
    print(f"wrote {outdir / 'macros.tex'}")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--bench", type=Path, action="append", default=None,
                   help="benchmark JSON; may be given more than once")
    p.add_argument("--correctness", type=Path)
    p.add_argument("--outdir", type=Path, default=Path(__file__).resolve().parent.parent / "results")
    args = p.parse_args()
    args.outdir.mkdir(parents=True, exist_ok=True)

    headline: dict[str, float] = {}
    merged = {"env": {}, "rows": []}
    for b in (args.bench or []):
        data = json.loads(b.read_text())
        merged["rows"].extend(data["rows"])
        merged["env"] = merged["env"] or data.get("env", {})
    if merged["rows"]:
        build_paper_tables(merged, args.outdir)
        # Per-(protocol, mode, dtype) renderings of the same measurements. The
        # manuscript does not \input these; they live one level down so that
        # results/ contains only what the paper actually uses.
        per_config = args.outdir / "per_config"
        per_config.mkdir(parents=True, exist_ok=True)
        headline = build_tables(merged, per_config)
        build_env(merged, args.outdir)
        build_macros(headline, args.outdir)
    if args.correctness and args.correctness.exists():
        build_correctness(json.loads(args.correctness.read_text()), args.outdir)


if __name__ == "__main__":
    main()
