#!/usr/bin/env python3
"""
Emit the paper's result tables from the measurement campaign already carried
out by the authors (RTX A6000, Apple M3 Pro, L40S).

This exists so the manuscript compiles with real numbers today. It is a
stop-gap: `bench.py` + `make_tables.py` overwrite exactly the same files from
freshly measured JSON, and the appendix says so. The tables below were
recorded as latency ratios with the fused kernel as the unit; here they are
re-expressed against the *reference* implementation, which is the honest
denominator for a paper claiming a speedup over it.

Usage
-----
    python seed_from_report.py                # writes ../results/*.tex
"""

from __future__ import annotations

import argparse
from pathlib import Path

LEVELS = [1, 2, 3, 4, 5]

HEADER = (
    "% Generated by scripts/seed_from_report.py from the authors' original\n"
    "% measurement campaign. Re-running scripts/bench.py followed by\n"
    "% scripts/make_tables.py regenerates this file from fresh measurements.\n"
)

# -----------------------------------------------------------------------------
# Measurements, verbatim from the campaign. Each entry is
#   (depthwise, dense, reference, fused)
# expressed as mean latency relative to the fused kernel (fused = 1.00), i.e.
# the number in the 'reference' slot is already the speedup of fused over the
# reference implementation.
# -----------------------------------------------------------------------------
RAW = {
    # backend, protocol, metric, dtype -> {level: (dw, dense, ref, fused)}
    ("cuda", "homogeneous", "latency", "fp32"): {
        1: (0.29, 0.58, 2.24, 1.00), 2: (0.27, 0.54, 2.72, 1.00),
        3: (0.26, 0.52, 2.82, 1.00), 4: (0.26, 0.52, 2.85, 1.00),
        5: (0.25, 0.51, 2.87, 1.00)},
    ("cuda", "homogeneous", "latency", "fp16"): {
        1: (0.31, 0.82, 2.99, 1.00), 2: (0.29, 0.77, 3.65, 1.00),
        3: (0.28, 0.75, 3.79, 1.00), 4: (0.28, 0.73, 3.83, 1.00),
        5: (0.27, 0.71, 3.84, 1.00)},
    ("cuda", "homogeneous", "memory", "fp32"): {
        1: (0.71, 0.95, 1.46, 1.00), 2: (0.67, 0.89, 1.50, 1.00),
        3: (0.65, 0.87, 1.47, 1.00), 4: (0.65, 0.87, 1.47, 1.00),
        5: (0.65, 0.87, 1.47, 1.00)},
    ("cuda", "homogeneous", "memory", "fp16"): {
        1: (0.71, 1.01, 1.46, 1.00), 2: (0.67, 0.95, 1.50, 1.00),
        3: (0.65, 0.93, 1.47, 1.00), 4: (0.65, 0.93, 1.47, 1.00),
        5: (0.65, 0.93, 1.47, 1.00)},
    ("cuda", "rfmatch", "latency", "fp32"): {
        1: (1.08, 1.96, 2.24, 1.00), 2: (1.00, 1.82, 2.72, 1.00),
        3: (0.98, 1.78, 2.83, 1.00), 4: (0.97, 1.77, 2.87, 1.00),
        5: (0.96, 1.75, 2.89, 1.00)},
    ("cuda", "rfmatch", "latency", "fp16"): {
        1: (2.13, 2.30, 2.96, 1.00), 2: (1.99, 2.15, 3.62, 1.00),
        3: (1.94, 2.10, 3.77, 1.00), 4: (1.90, 2.06, 3.85, 1.00),
        5: (1.86, 2.02, 3.84, 1.00)},
    ("cuda", "rfmatch", "memory", "fp32"): {
        1: (0.70, 1.06, 1.46, 1.00), 2: (0.66, 0.99, 1.49, 1.00),
        3: (0.65, 0.98, 1.47, 1.00), 4: (0.64, 0.97, 1.46, 1.00),
        5: (0.64, 0.97, 1.46, 1.00)},
    ("cuda", "rfmatch", "memory", "fp16"): {
        1: (0.70, 1.10, 1.46, 1.00), 2: (0.66, 1.02, 1.49, 1.00),
        3: (0.65, 1.01, 1.47, 1.00), 4: (0.64, 1.00, 1.46, 1.00),
        5: (0.64, 1.00, 1.46, 1.00)},

    ("triton", "homogeneous", "latency", "fp32"): {
        1: (0.38, 0.87, 2.71, 1.00), 2: (0.32, 0.74, 3.09, 1.00),
        3: (0.29, 0.66, 3.03, 1.00), 4: (0.26, 0.60, 2.90, 1.00),
        5: (0.24, 0.56, 2.81, 1.00)},
    ("triton", "homogeneous", "latency", "fp16"): {
        1: (0.35, 0.89, 2.94, 1.00), 2: (0.28, 0.72, 3.16, 1.00),
        3: (0.24, 0.62, 3.00, 1.00), 4: (0.21, 0.55, 2.81, 1.00),
        5: (0.19, 0.51, 2.69, 1.00)},
    ("triton", "rfmatch", "latency", "fp32"): {
        1: (1.32, 3.14, 2.77, 1.00), 2: (1.08, 2.56, 3.08, 1.00),
        3: (1.00, 2.35, 3.09, 1.00), 4: (0.91, 2.15, 2.94, 1.00),
        5: (0.86, 2.02, 2.84, 1.00)},
    ("triton", "rfmatch", "latency", "fp16"): {
        1: (2.17, 2.68, 2.98, 1.00), 2: (1.75, 2.15, 3.16, 1.00),
        3: (1.53, 1.88, 3.01, 1.00), 4: (1.39, 1.71, 2.87, 1.00),
        5: (1.26, 1.55, 2.69, 1.00)},

    ("metal", "homogeneous", "latency", "fp32"): {
        1: (0.80, 10.06, 2.05, 1.00), 2: (0.71, 8.85, 2.34, 1.00),
        3: (0.68, 8.44, 2.40, 1.00), 4: (0.64, 7.97, 2.37, 1.00),
        5: (0.61, 7.67, 2.31, 1.00)},
    ("metal", "homogeneous", "latency", "fp16"): {
        1: (1.11, 12.99, 2.05, 1.00), 2: (0.93, 10.73, 2.13, 1.00),
        3: (0.88, 10.32, 2.20, 1.00), 4: (0.85, 9.90, 2.20, 1.00),
        5: (0.80, 9.36, 2.15, 1.00)},
    ("metal", "rfmatch", "latency", "fp32"): {
        1: (0.82, 10.29, 2.17, 1.00), 2: (0.72, 8.95, 2.36, 1.00),
        3: (0.68, 8.46, 2.39, 1.00), 4: (0.65, 8.10, 2.38, 1.00),
        5: (0.62, 7.78, 2.36, 1.00)},
    ("metal", "rfmatch", "latency", "fp16"): {
        1: (0.69, 6.65, 1.92, 1.00), 2: (0.55, 5.56, 1.83, 1.00),
        3: (0.62, 6.16, 2.53, 1.00), 4: (0.54, 5.69, 2.16, 1.00),
        5: (0.51, 5.23, 2.24, 1.00)},
}

BACKEND_NAME = {"cuda": "CUDA", "triton": "Triton", "metal": "Metal"}
DTYPE_TEX = {"fp32": r"\texttt{fp32}", "fp16": r"\texttt{fp16}"}


def speedup_over_reference(entry):
    """Re-normalise a (dw, dense, ref, fused) row so that reference = 1.00."""
    dw, dense, ref, fused = entry
    return {"depthwise": ref / dw, "dense": ref / dense,
            "reference": 1.0, "fused": ref / fused}


def f(v: float) -> str:
    return f"{v:.2f}"


def wrap(body, caption, label, cols):
    return "\n".join([r"\begin{table}[t]", r"\centering",
                      rf"\caption{{{caption}}}", rf"\label{{{label}}}",
                      rf"\begin{{tabular}}{{{cols}}}", r"\toprule",
                      *body, r"\bottomrule", r"\end{tabular}",
                      r"\end{table}", ""])


def lvlhead(first: str, span_from: int) -> list:
    n = len(LEVELS)
    return [rf"\multirow{{2}}{{*}}{{{first}}} & \multicolumn{{{n}}}{{c}}"
            r"{Decomposition levels $L$} \\",
            rf"\cmidrule(lr){{{span_from}-{span_from + n - 1}}}",
            " & " + " & ".join(str(l) for l in LEVELS) + r" \\", r"\midrule"]


# ------------------------------------------------------------------ memory
def tab_memory(outdir):
    body = lvlhead("Precision", 2)
    for dt in ("fp32", "fp16"):
        r = RAW[("cuda", "homogeneous", "memory", dt)]
        body.append(DTYPE_TEX[dt] + " & "
                    + " & ".join(f(r[l][2]) + r"$\times$" for l in LEVELS) + r" \\")
    return (outdir / "tab_memory.tex").write_text(HEADER + wrap(
        body,
        r"Peak allocated memory of the reference implementation relative to the fused "
        r"layer (higher means the reference needs more), CUDA backend on an RTX~A6000. "
        r"The reduction is essentially flat in $L$ because the dominant saved "
        r"allocation is the level-1 coefficient tensor, which is four times larger "
        r"than all deeper levels combined.",
        "tab:memory", "l" + "c" * len(LEVELS)))


# ----------------------------------------------------------------- context
def tab_context(outdir, protocol, fname, label, caption):
    body = [r"\multirow{2}{*}{Method} & \multirow{2}{*}{Precision} & "
            rf"\multicolumn{{{len(LEVELS)}}}{{c}}{{Decomposition levels $L$}} \\",
            rf"\cmidrule(lr){{3-{2 + len(LEVELS)}}}",
            " & & " + " & ".join(str(l) for l in LEVELS) + r" \\", r"\midrule"]
    kdw = "7" if protocol == "rfmatch" else "3"
    labels = [("depthwise", rf"Depthwise conv, $k{{=}}{kdw}$"),
              ("dense", rf"Dense conv, $k{{=}}{kdw}$"),
              ("reference", r"WTConv, reference"),
              ("fused", r"WTConv, \textbf{fused}")]
    for key, lab in labels:
        for dt in ("fp32", "fp16"):
            r = RAW[("cuda", protocol, "latency", dt)]
            vals = [speedup_over_reference(r[l])[key] for l in LEVELS]
            body.append((lab if dt == "fp32" else "") + " & " + DTYPE_TEX[dt] + " & "
                        + " & ".join(f(v) + r"$\times$" for v in vals) + r" \\")
        body.append(r"\addlinespace[2pt]")
    return (outdir / f"{fname}.tex").write_text(HEADER + wrap(
        body, caption, label, "ll" + "c" * len(LEVELS)))


# ---------------------------------------------------------------- backends
def tab_backends(outdir):
    body = [r"\multirow{2}{*}{Backend} & \multirow{2}{*}{Hardware} & "
            r"\multirow{2}{*}{Precision} & "
            rf"\multicolumn{{{len(LEVELS)}}}{{c}}{{Decomposition levels $L$}} \\",
            rf"\cmidrule(lr){{4-{3 + len(LEVELS)}}}",
            " & & & " + " & ".join(str(l) for l in LEVELS) + r" \\", r"\midrule"]
    for be, hw in (("cuda", "RTX A6000"), ("triton", "RTX A6000"), ("metal", "M3 Pro")):
        for dt in ("fp32", "fp16"):
            r = RAW.get((be, "homogeneous", "latency", dt))
            if not r:
                continue
            body.append(f"{BACKEND_NAME[be] if dt == 'fp32' else ''} & "
                        f"{hw if dt == 'fp32' else ''} & " + DTYPE_TEX[dt] + " & "
                        + " & ".join(f(r[l][2]) + r"$\times$" for l in LEVELS) + r" \\")
        body.append(r"\addlinespace[2pt]")
    return (outdir / "tab_backends.tex").write_text(HEADER + wrap(
        body,
        r"Speedup over the reference implementation for all three realisations of the "
        r"same reformulation, homogeneous protocol ($k{=}3$). The Metal figures are "
        r"measured against PyTorch's MPS backend, which is markedly less mature than "
        r"cuDNN; they demonstrate portability of the formulation rather than a "
        r"like-for-like vendor comparison.",
        "tab:backends", "lll" + "c" * len(LEVELS)))


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--outdir", type=Path,
                   default=Path(__file__).resolve().parent.parent / "results")
    a = p.parse_args()
    a.outdir.mkdir(parents=True, exist_ok=True)

    tab_memory(a.outdir)
    tab_backends(a.outdir)
    tab_context(
        a.outdir, "homogeneous", "tab_context", "tab:context",
        r"Forward latency of every method relative to the reference WTConv "
        r"($1.00\times$; higher is faster), all at $k{=}3$, CUDA backend on an "
        r"RTX~A6000. Fusion recovers most---but not all---of the gap to a plain "
        r"depthwise convolution, which is the honest statement of what the layer "
        r"now costs.")
    tab_context(
        a.outdir, "rfmatch", "tab_rfmatch", "tab:rfmatch",
        r"Receptive-field-matched comparison: WTConv at $k{=}3$ against plain "
        r"convolutions at $k{=}7$, all relative to the reference WTConv "
        r"($1.00\times$; higher is faster), CUDA backend on an RTX~A6000. The "
        r"reference WTConv is \emph{slower} than the dense convolution it is meant "
        r"to replace; the fused layer is faster than it at every level.")
    print(f"wrote 5 tables to {a.outdir}")


if __name__ == "__main__":
    main()
